[Launcher]
Columns=8
Rows=5
IconSize=96
HGap=24
VGap=24
FontSize=12
FontName=CaskaydiaCoveNerdFont-SemiBold
NameMaxLen=20
Terminal=kitty

[folder1]
Name=Gaming
Icon=applications-games
Columns=3
Rows=3
Apps=steam,org.prismlauncher.PrismLauncher, Factorio

[folder2]
Name=CAD & 3D
Icon=applications-engineering
Columns=3
Rows=3
Apps=org.freecad.FreeCAD,BambuStudio,blender,alcom

[folder3]
Name=Unity & VRChat
Icon=applications-development
Columns=3
Rows=3
Apps=unityhub,ALCOM,VRChat

[folder4]
Name=Media
Icon=applications-multimedia
Columns=3
Rows=3
Apps=vlc,mpv,spotify,org.gnome.Loupe,org.qbittorrent.qBittorrent.desktop,dupeguru

[folder5]
Name=Development
Icon=applications-development
Columns=3
Rows=3
Apps=jetbrains-idea-ce,cmake-gui,nvim,vim,virtualbox

[folder6]
Name=System
Icon=applications-system
Columns=3
Rows=3
Apps=htop,nvtop,org.gnome.DiskUtility,rog-control-center,com.saivert.pwvucontrol,org.gnome.font-viewer,fcitx5-configtool,org.fcitx.Fcitx5,battop

[page1]
Apps=firefox,discord,kitty,org.gnome.Nautilus,anki,tagainijisho,org.darktable.darktable,chromium,com.github.PintaProject.Pinta,folder1,folder2,folder3,folder4,folder5,folder6
